services:

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    # runtime: nvidia
    env_file:
      - ./base.env
      - ./plex/plex.env
    volumes:
      - ./plex/config:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/movies:/movies
      - ./plex/transcode:/transcode

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    env_file:
      - ./base.env
    volumes:
      - ./transmission/config:/config
      - ${MEDIA_PATH}/transmission:/data/transmission
      - ./transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 9091:9091

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    env_file:
      - ./base.env
    volumes:
      - ./sabnzbd/config:/config
      - ${MEDIA_PATH}/usenet:/data/usenet
    ports:
      - 8080:8080

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    env_file:
      - ./base.env
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - transmission
    env_file:
      - ./base.env
    volumes:
      - ./sonarr/config:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 8989:8989
    links:
      - "plex"

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - transmission
    env_file:
      - ./base.env
    volumes:
      - ./radarr/config:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 7878:7878
    links:
      - "plex"

  kavita:
    image: jvmilazz0/kavita
    container_name: kavita
    env_file:
      - ./base.env
    volumes:
      - ${MEDIA_PATH}/comics:/comics
      - ./kavita/config:/kavita/config
    ports:
      - 5000:5000
    restart: unless-stopped

  mylar:
    image: lscr.io/linuxserver/mylar3
    container_name: mylar
    env_file:
      - ./base.env
    volumes:
      - ./mylar/config:/config
      - ${MEDIA_PATH}:/data
      - /home/tim/comics:/opt
    ports:
      - 8090:8090
    restart: unless-stopped

  doplarr:
    image: lscr.io/linuxserver/doplarr
    container_name: doplarr
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./base.env
      - ./doplarr/doplarr.env
    volumes:
      - ./doplarr/config:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - PGID=${GID}
      - UID=${UID}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - 8191:8191
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    env_file:
      - ./base.env
      - ./swag/swag.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./swag:/config
  #  gui:
  #    image: node:10
  #    working_dir: /usr/src/app
  #    restart: unless-stopped 
  #    environment:
  #      NODE_ENV: development
  #    command: npm start
  #    volumes:
  #      - ./gui:/usr/src/app
  #    ports:
  #      - 8080:8080  

  #nginx:
  # image: nginx
  # restart: unless-stopped 
  # environment:
  #   - NGINX_PORT=80
  # # - NGINX_HOST=10.0.0.3
  # depends_on:
  #   - radarr
  #   - sonarr
  #   - transmission
  # volumes:
  #   - ./nginx/conf.d/:/etc/nginx/conf.d
  #   - ./nginx/config/:/config/nginx/
  # command: /bin/bash -c "exec nginx -g 'daemon off;'"
  # ports:
  #   - 80:80
