version: '2.1'

services:

  plex:
    image: lscr.io/linuxserver/plex
    restart: unless-stopped 
    network_mode: host
    runtime: nvidia
    devices: 
      - /dev/dri:/dev/dri
    environment:
      - VERSION=public
      - NVIDIA_VISIBLE_DEVICES=all
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./plex/config:/config
      - ./sonarr/tv:/tv
      - ./radarr/movies:/movies
      - ./plex/transcode:/transcode

  transmission:
    image: lscr.io/linuxserver/transmission
    restart: unless-stopped 
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 9091:9091

  jackett:
    image: lscr.io/linuxserver/jackett
    restart: unless-stopped 
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - AUTO_UPDATE=true
      - TZ=America/Chicago
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
        #    sysctls:
        #      - net.ipv6.conf.all.disable_ipv6=1

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    ports:
      - 8191:8191
        #    sysctls:
        #      - net.ipv6.conf.all.disable_ipv6=1

  sonarr:
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped 
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
      - ./transmission/downloads:/downloads
      - ./sonarr/tv/cody:/cody
    ports:
      - 8989:8989
    links:
      - "plex"

  radarr:
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped 
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./transmission/downloads:/downloads
      - ./radarr/movies/cody:/cody
    ports:
      - 7878:7878
    links:
      - "plex"

  gui:
    image: node:10
    working_dir: /usr/src/app
    restart: unless-stopped 
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./gui:/usr/src/app
    ports:
      - 8080:8080

  nginx:
    image: nginx
    restart: unless-stopped 
    environment:
      - NGINX_PORT=80
    # - NGINX_HOST=10.0.0.3
    depends_on:
      - radarr
      - sonarr
      - jackett
      - transmission
      - gui
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/config/:/config/nginx/
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
      - 80:80
