version: '3'

services:

  plex:
    image: linuxserver/plex:latest
    restart: on-failure
    network_mode: host
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./plex/config:/config
      - ./sonarr/tv:/data/tvshows
      - ./radarr/movies:/data/movies
      - ./lidarr/music:/data/music
      - ./plex/transcode:/transcode

  transmission:
    image: linuxserver/transmission:latest
    restart: on-failure
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 9091:9091

  jackett:
    image: linuxserver/jackett:latest
    restart: on-failure
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117

  sonarr:
    image: linuxserver/sonarr:latest
    restart: on-failure
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
      - ./transmission/downloads:/downloads
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr:latest
    restart: on-failure
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=America/Chicago
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./transmission/downloads:/downloads
    ports:
      - 7878:7878

  gui:
    image: node:10
    working_dir: /usr/src/app
    restart: on-failure
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./gui:/usr/src/app
    ports:
      - 8080:8080

  nginx:
    image: nginx
    restart: on-failure
    environment:
      - NGINX_PORT=80
    # - NGINX_HOST=10.0.0.3
    depends_on:
      - radarr
      - sonarr
      - lidarr
      - jackett
      - transmission
      - gui
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/config/:/config/nginx/
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
      - 80:80
