version: '2.0'
services:

  plex:
    image: linuxserver/plex:latest
    restart: on-failure
    network_mode: host
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./plex/config:/config
      - ./sonarr/tv:/data/tvshows
      - ./radarr/movies:/data/movies
      - ./lidarr/music:/data/music
      - ./plex/transcode:/transcode

  transmission:
    image: linuxserver/transmission:latest
    restart: on-failure
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    expose:
      - 9091
    ports:
      - 51413:51413
      - 51413:51413/udp

  jackett:
    image: linuxserver/jackett:latest
    restart: on-failure
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    expose:
      - 9117

  sonarr:
    image: linuxserver/sonarr:latest
    restart: on-failure
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv
      - ./transmission/downloads:/downloads
    expose:
      - 8989

  radarr:
    image: linuxserver/radarr:latest
    restart: on-failure
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./transmission/downloads:/downloads
    expose:
      - 7878

  lidarr:
    image: linuxserver/lidarr:latest
    restart: on-failure
    depends_on:
      - transmission
      - jackett
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ./lidarr/config:/config
      - ./lidarr/music:/music
      - ./transmission/downloads:/downloads
    expose:
      - 8686

  gui:
    image: node:10
    working_dir: /usr/src/app
    restart: on-failure
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./gui:/usr/src/app
    expose:
      - 8080

  nginx:
    image: nginx
    restart: on-failure
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=10.0.0.3
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/reverse_proxy.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80
